### ISSUE TITLE
V3: Cannot call `setCookie`

### ISSUE THREAD

**Issue by Landschaft** [capacitor-community/http#105]
**Describe the bug**
We're upgrading to Capacitor 3 and use [HTTP/capacitor-v3](https://github.com/capacitor-community/http/tree/capacitor-v3). 

In our app we call the `setCookie()` method as below:

    Http.setCookie(cookieName, "localhost", {
      url: url,
      expires: expires.toUTCString()
    });

This results in the following error:

    Error: Invalid URL. Check that "server" is set correctly in your capacitor.config.json file
        at Object.cap.fromNative (vendor.js:127775)
        at <anonymous>:1:18

Debugging `HTTP.setCookie(PluginCall call)` shows that `call.data` is an empty JSObject.

Are we calling `setCookie()` in a wrong manner? According to `definitions.ts` we think we do it right:

      setCookie(key: string, value: any, options?: HttpCookieOptions): Promise<void>;

**Capacitor**
- 3.0.0-beta.6

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 10.15.7

**Smartphone (please complete the following information):**
 - Device: Android emulator, iOS Simulator
 - OS: Android, iOS
 - Version API 30, 14.3

**Comment by thomasvidas** [comment]
This change was made due to 3rd party cookies not being supported on iOS. The `server` variable is automatically pulled from `capConfig.getServerUrl()` on Android and `capConfig?.serverURL` on iOS.

Previously you didn't have to set server in your config, but that resulted in differences between Android and iOS since 3rd party cookies on Android worked fine on older versions (but won't in the future). In order to future proof and have the same experience across Android and iOS, I made it so that you have to set the server manually in your `capacitor.config.ts` or `capacitor.config.json` file.

I'll document this in the README to make it more clear. The core team has an issue to better handle cookie management in iOS/Android, but for now this is outside of the scope of this plugin.

I'll close this for now, but please reopen if you're still having issues and your `server` variable in the [Capacitor Config](https://capacitorjs.com/docs/config) is set correctly

**Comment by Landschaft** [comment]
@thomasvidas thank you for looking into this

I would like to reopen but don't have the necessary rights to do so.

**Comment by Landschaft** [comment]
Let me clarify.

The setCookie method takes three parameters:

`setCookie(key: string, value: any, options?: HttpCookieOptions): Promise<void>;`

This is how we call it:

`Http.setCookie("someCookieName", "localhost", { url: url, expires: expires.toUTCString() } );

This is how the call is received in MessageHandler.postMessage:

`{"callbackId":"41716569","pluginId":"Http","methodName":"setCookie","options":"someCookieName"}`

The problem ist that `options` contains only the cookie name, all other parameters are lost.

**Comment by Landschaft** [comment]
> In order to future proof and have the same experience across Android and iOS, I made it so that you have to set the server 
> manually in your capacitor.config.ts or capacitor.config.json file.

Does this mean, that `server.url` no longer mandatory but required when using the HTTP plugin? This is against the [documentation](https://capacitorjs.com/docs/v3/config#capacitor-configuration) of this property that says: 

> **This is not intended for use in production.**

**Comment by thomasvidas** [comment]
I have reverted the changes for the server and the API is reverted the old style for the most part. I'll put the new version on npm soon

**Comment by Landschaft** [comment]
> I'll put the new version on npm soon

Hi @thomasvidas _how_ soon will this be? I've been waiting desperately for this :-)

**Comment by thomasvidas** [comment]
This should already be available on npm in `1.0.0-alpha.4` under `@capacitor-community/http@next`

**Comment by Landschaft** [comment]
That's great news! I wasn't aware of that new version since there is not tag for it under https://github.com/capacitor-community/http/tags

How is one supposed to discover new versions?

**Comment by thomasvidas** [comment]
My focus in the past month has mostly been trying to get some fixes for Capacitor 3 RC out the door so the docs/releases on here have been a little lacking 😅. In the future I'll be better about updating this repo.
