### ISSUE TITLE
Http calls to Api are no longer sent after update to version 3

### ISSUE THREAD

**Issue by andreastoermer** [capacitor-community/http#129]
**Describe the bug**
I am not 100% sure if this is really a bug or if I am not able to integrate the plugin correctly.

Namely, in the past I have used Capacitor 2.x with the HTTP plugin in version 0.3.1. It all worked flawlessly.

In the course of the final release of Capacitor 3 I have now updated both capacitor and the plugin (to version 1.0.0).

Now I start the application in the IOS simulator of XCode no Api Call works anymore. After debugging with Safari support I found out the reason: "Http.post()" is not implemented on ios".

However, I could not find anything in the manual regarding this, do I still need to enable the plugin for IOS? 

Thanks in advance for your help.

**To Reproduce**
1. Use React Ionic app with capacitor 2.x and Capacitor HTTP Plugin 0.3.1
2. Upgrade to Capacitor 3 and Capacitor HTTP Plugin 1.0
3. Start ios Run with XCode

**Expected behavior**
The Api Call should be executed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS M1 11.3
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 14.1

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] IPhone 12 Pro XCode Emulator
 - OS: [e.g. iOS8.1]IOS 14 XCode Emulator

**Comment by ultimate-tester** [comment]
Just trying to help, I'm also kind of new to this, but I had similar issues with other plugins.
I had 2 mistakes on my side:

- Since v3, all plugins are auto loading so the MainActivity can be left completely blank
- I occasionally forgot to run `npx cap sync android` which meant the android app never got the plugin references

**Comment by andreastoermer** [comment]
My described problem exists with IOS, syncs were executed. I even removed the existing IOS integration and had it regenerated for me (speak virgin IOS integration), still I have this problem :)

**Comment by mediantiba** [comment]
Hi, I had the same problem, the HTTP plugin stopped working on my real device (Android) after upgrading to Capacitor 3. I've solved the problem by using the old API, apparently, it's still supported. So instead of `HTTP.get()` and `HTTP.post()` I used `HTTP.request()` passing in the method name as a property and it worked!

Hopefully these new methods should be supported in the future!

**Comment by andreastoermer** [comment]
Thanks, it now works :) I will close this now.

**Comment by MVDeveloper1** [comment]
> Hi, I had the same problem, the HTTP plugin stopped working on my real device (Android) after upgrading to Capacitor 3. I've solved the problem by using the old API, apparently, it's still supported. So instead of `HTTP.get()` and `HTTP.post()` I used `HTTP.request()` passing in the method name as a property and it worked!
> 
> Hopefully these new methods should be supported in the future!

I also had the same problem now, HTTP.get() was not working, I was getting an error "HTTP.get() is not implemented in Android", but after changing to HTTP.request() this error was fixed.
