### ISSUE TITLE
What's the difference between using this plugin instead of HttpClient from Angular?

### ISSUE THREAD

**Issue by IgorSamer** [capacitor-community/http#138]
I searched but didn't find an explanation of why to use this plugin instead of HttpService (Angular). Could someone explain to me what are the differences/advantages of using this native plugin?

**Comment by thomasvidas** [comment]
A big reason is that Android and iOS got rid of third party cookies. By default, capacitor apps are served from `capacitor://localhost` and `http://localhost` on iOS and Android respectively. Meaning that you can't save cookies via the normal `document.cookie = blah` way.

This library also uses the native libraries which are _slightly_ more performant than using the web libraries due to less overhead.

If you don't require cookie based authentication and don't need super optimized performance then you probably don't need this library 😄

**Comment by kirillgroshkov** [comment]
What about CORS? My expectation is that we can bypass CORS preflight requests with this Plugin, versus using browser `fetch` that will do a preflight for every damn request. Is that a reason to use this Plugin?

Preflight request is like ~50ms on a fast internet connection (and node.js express-cors server hosted on GCP). So, by removing CORS it can speedup ALL your http request by ~50ms. Right?

**Comment by thomasvidas** [comment]
This does indeed bypass CORs, yes. Since it is not a web browser making the request
